dist: trusty
language: node_js
node_js:
- node
addons:
  sonarcloud:
    organization: nickmanbear
    token:
      secure: MljEs5al1mEuS/pFNy/JrENA5C7BEqR0RA+1GTPLEG2dFZp86UfmC3hBUAXRMlJ/1f5ydoGK7oAxzC4R2kT/8f3AQM9CXWsD4ccvJp9VspqTE6OaZ495CW+nmycWyL5Vq1xXqnvV8gJMJ8BGdrdU/5deh9JDioqVvKlCdDdFpz3oUMWvs6W+yvYtwNjEczOlqDlEnL1Cnk/I2l0mREGvl/41CpUjWIkG1PhdcEMJrXAqJNY5GsB9R+gUHPcreCviLEF4+wQLWSb+AyRvvXLLKHGyyz522a77gvGE0BXQIjW+jh4wZySjik4QYp55oqwvdWlBS3YjzER1IPnmNKkS0x0BUjDSDOTc/eEV5rDkNXuL4Ul50pLX/F8gio2yyHvJKHQzVzRpjOJyXq3aIWqn00F8I50WZRPzPW4K1VuaPlVKLfzjoLNZAMmp7GMEAjk+SH9ebGq9WfJBF6eITj23TtW4M7e50v57IrSw6OLtRp9BBfFzrOQ5qQ8YSM0M+x/oon+PJUWIa2L7ZUP5L6drPvmV1spVUU9iqu/teSnNk2OwsLSI9+fHyqXUM0yQf/koUFvF8Ss2JYlBCzRRkXHbwmOoahKTyHmj1F4RfYIiQrOchYzKoKk1FPnu6QM8nCCb09ygPrMS0Y5kIsElUEn1EVNUiMZN3MZ1GPAI4bpL71Y=
env:
- BUILD_DIR="~/builds/frontend-test/"
cache: npm
script:
- sonar-scanner
before_install:
- openssl aes-256-cbc -K $encrypted_c28ab4f155ee_key -iv $encrypted_c28ab4f155ee_iv
  -in id_rsa-travis-ci.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- ssh-add ./id_rsa
- echo -e "Host swarm.cherement.nl\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo $BUILD_DIR
- ssh -i ./id_rsa travis-ci@swarm.cherement.nl pwd
services:
- docker
jobs:
  include:
  - stage: Tests
    script:
    - npm test
  - stage: Test Build Docker image
    script:
    - npm run build
    - docker build -t jak/frontend .
  - stage: Deployment-Test.server
    if: branch = dev
    script:
    - npm run build
    - rsync -au -e "ssh -i ./id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      --progress dist travis-ci@swarm.cherement.nl:$BUILD_DIR\dist
    - rsync -au -e "ssh -i ./id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      --progress Dockerfile travis-ci@swarm.cherement.nl:$BUILD_DIR\Dockerfile
    - ssh -i ./id_rsa travis-ci@swarm.cherement.nl $BUILD_DIR\rebuild-docker.sh
  - stage: Deployment-prod.server
    if: branch = master
    env:
    - BUILD_DIR="~/builds/frontend-prod/"
    script:
    - npm run build
    - rsync -au -e "ssh -i ./id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      --progress dist travis-ci@swarm.cherement.nl:$BUILD_DIR\dist
    - rsync -au -e "ssh -i ./id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      --progress Dockerfile travis-ci@swarm.cherement.nl:$BUILD_DIR\Dockerfile
    - ssh -i ./id_rsa travis-ci@swarm.cherement.nl $BUILD_DIR\rebuild-docker.sh
